"""Agregar tabla de configuraciones

Revision ID: 09f501cbfdbc
Revises: 2391538e1a9b
Create Date: 2026-06-27 01:16:08.035409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f501cbfdbc'
down_revision: Union[str, Sequence[str], None] = '2391538e1a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_sistema',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('nombre_descriptivo', sa.String(length=150), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_sistema')
    # ### end Alembic commands ###
