"""Agregar campo de turno para los docentes

Revision ID: 2391538e1a9b
Revises: 5ceda0190711
Create Date: 2026-06-22 17:21:13.885436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2391538e1a9b'
down_revision: Union[str, Sequence[str], None] = '5ceda0190711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', 'MIXTO', name='turno'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docentes', 'turno')
    # ### end Alembic commands ###
