"""Agregar numero_periodo a materias y grupos_abiertos

Revision ID: 311039306d0a
Revises: 4f2a1ad64cea
Create Date: 2026-06-16 22:31:46.292143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '311039306d0a'
down_revision: Union[str, Sequence[str], None] = '4f2a1ad64cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_abiertos', sa.Column('numero_periodo', sa.Integer(), nullable=False))
    op.drop_column('grupos_abiertos', 'semestre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_abiertos', sa.Column('semestre', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('grupos_abiertos', 'numero_periodo')
    # ### end Alembic commands ###
