"""Agregar campos de mes_inicio, mes_final y anio en ciclos_escolares

Revision ID: 337b8d4a62c7
Revises: 311039306d0a
Create Date: 2026-06-16 23:51:25.892312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '337b8d4a62c7'
down_revision: Union[str, Sequence[str], None] = '311039306d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciclos_escolares', sa.Column('mes_inicio', sa.Integer(), nullable=False))
    op.add_column('ciclos_escolares', sa.Column('mes_final', sa.Integer(), nullable=False))
    op.add_column('ciclos_escolares', sa.Column('anio', sa.Integer(), nullable=False))
    op.alter_column('ciclos_escolares', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ciclos_escolares', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ciclos_escolares', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('ciclos_escolares', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('ciclos_escolares', 'anio')
    op.drop_column('ciclos_escolares', 'mes_final')
    op.drop_column('ciclos_escolares', 'mes_inicio')
    # ### end Alembic commands ###
