"""Agregar tipo_periodo a planes_estudio

Revision ID: 4f2a1ad64cea
Revises: 643378939257
Create Date: 2026-06-16 22:08:53.787046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f2a1ad64cea'
down_revision: Union[str, Sequence[str], None] = '643378939257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materias', sa.Column('numero_periodo', sa.Integer(), nullable=False))
    op.drop_column('materias', 'semestre')
    op.add_column('plan_estudios', sa.Column('tipo_periodo', sa.Enum('SEMESTRAL', 'CUATRIMESTRAL', 'MODULAR', name='tipoperiodo'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_estudios', 'tipo_periodo')
    op.add_column('materias', sa.Column('semestre', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('materias', 'numero_periodo')
    # ### end Alembic commands ###
