"""Ajustes

Revision ID: 5ceda0190711
Revises: eb21bba502c1
Create Date: 2026-06-22 16:24:45.268445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ceda0190711'
down_revision: Union[str, Sequence[str], None] = 'eb21bba502c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asignaciones_carga', 'estado_asignacion',
               existing_type=mysql.ENUM('PENDIENTE', 'ASIGNADA', 'SABATICO', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDIENTE', 'ASIGNADA', 'DESCARGADA', name='estadoasignacion'),
               existing_nullable=False)
    op.alter_column('grupos_abiertos', 'numero_periodo',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('materias', 'numero_periodo',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materias', 'numero_periodo',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('grupos_abiertos', 'numero_periodo',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('asignaciones_carga', 'estado_asignacion',
               existing_type=sa.Enum('PENDIENTE', 'ASIGNADA', 'DESCARGADA', name='estadoasignacion'),
               type_=mysql.ENUM('PENDIENTE', 'ASIGNADA', 'SABATICO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
