"""Creacion inicial de tablas

Revision ID: d2da5d1b2d97
Revises: 
Create Date: 2026-06-07 23:53:35.927223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2da5d1b2d97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_conocimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_docentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('siglas', sa.String(length=10), nullable=False),
    sa.Column('hsm_base', sa.Integer(), nullable=False),
    sa.Column('nivel_prioridad', sa.Integer(), nullable=False),
    sa.Column('es_comodin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ciclos_escolares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programas_educativos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plan_estudios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('programa_educativo_id', sa.Integer(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['programa_educativo_id'], ['programas_educativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_institucional', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_institucional')
    )
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('plaza', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('hsm_personalizadas', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'COMISIONADO', 'LICENCIA', 'SABATICO', 'VACANTE', name='estatusdocenteenum'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_docentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_asignatura', sa.String(length=150), nullable=False),
    sa.Column('plan_estudios_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=5), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', 'MIXTO', name='turnoenum'), nullable=False),
    sa.Column('hsm', sa.Integer(), nullable=False),
    sa.Column('area_conocimiento_id', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('VACANTE', 'ASIGNADA', 'EN_COMODIN', name='estatusmateriaenum'), nullable=False),
    sa.ForeignKeyConstraint(['area_conocimiento_id'], ['areas_conocimiento.id'], ),
    sa.ForeignKeyConstraint(['plan_estudios_id'], ['plan_estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones_carga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_titular_id', sa.Integer(), nullable=False),
    sa.Column('docente_temporal_id', sa.Integer(), nullable=True),
    sa.Column('ciclo_escolar_id', sa.Integer(), nullable=False),
    sa.Column('estado_asignacion', sa.Enum('NORMAL', 'RESERVADA_SABATICO', 'LIBERADA_TEMPORAL', 'RESTITUIDA', 'COMODIN', name='estadoasignacionenum'), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_escolar_id'], ['ciclos_escolares.id'], ),
    sa.ForeignKeyConstraint(['docente_temporal_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['docente_titular_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docentes_areas_conocimiento',
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('area_conocimiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_conocimiento_id'], ['areas_conocimiento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docente_id', 'area_conocimiento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docentes_areas_conocimiento')
    op.drop_table('asignaciones_carga')
    op.drop_table('materias')
    op.drop_table('docentes')
    op.drop_table('usuarios')
    op.drop_table('plan_estudios')
    op.drop_table('roles')
    op.drop_table('programas_educativos')
    op.drop_table('ciclos_escolares')
    op.drop_table('categorias_docentes')
    op.drop_table('areas_conocimiento')
    # ### end Alembic commands ###
