"""Ajustes asignaciones y descargas

Revision ID: eb21bba502c1
Revises: 337b8d4a62c7
Create Date: 2026-06-18 23:23:22.699842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb21bba502c1'
down_revision: Union[str, Sequence[str], None] = '337b8d4a62c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones_carga', sa.Column('motivo_descarga', sa.String(length=100), nullable=True))
    op.add_column('asignaciones_otras_actividades', sa.Column('ciclo_escolar_id', sa.BigInteger(), nullable=False))
    op.add_column('asignaciones_otras_actividades', sa.Column('horas_asignadas', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'asignaciones_otras_actividades', 'ciclos_escolares', ['ciclo_escolar_id'], ['id'])
    op.alter_column('ciclos_escolares', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('otras_actividades', 'hsm',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otras_actividades', 'hsm',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('ciclos_escolares', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_constraint(None, 'asignaciones_otras_actividades', type_='foreignkey')
    op.drop_column('asignaciones_otras_actividades', 'horas_asignadas')
    op.drop_column('asignaciones_otras_actividades', 'ciclo_escolar_id')
    op.drop_column('asignaciones_carga', 'motivo_descarga')
    # ### end Alembic commands ###
