"""Agregar campo valor a ConfiguracionSistema

Revision ID: f6712b29efa7
Revises: 09f501cbfdbc
Create Date: 2026-06-27 01:25:08.672955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6712b29efa7'
down_revision: Union[str, Sequence[str], None] = '09f501cbfdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_sistema', sa.Column('valor', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_sistema', 'valor')
    # ### end Alembic commands ###
