from .actividades import asignar_otra_actividad, eliminar_asignacion_otra_actividad
from .carga_academica import vincular_materia_a_docente, desvincular_materia
from .catalogos import buscar_docentes, obtener_catalogos_base
from .descargas import asignar_descarga, remover_descarga
from .disponibilidad import obtener_materias_disponibles
from .sugerencias import obtener_materias_sugeridas
from .tablero import obtener_tablero_docente
from .validaciones import _verificar_limite_hsm
from .resumen import obtener_resumen_carga_docentes, obtener_vacantes_ciclo_activo
from .reportes import generar_reporte_carga_html, generar_reporte_pad_html

